language: julia
os:
    - osx
    - linux
julia:
    - 1.3
notifications:
    email: false
env:
  matrix:
    - JULIA_NUM_THREADS=1
    - JULIA_NUM_THREADS=2
jobs:
  include:
    - stage: "Documentation"
      julia: 1.3
      os: linux
      script:
        - julia --project=docs/docs2 -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));Pkg.develop(PackageSpec(url="https://github.com/esa-esdl/ESDLPlots.jl"));'
        - julia --project=docs -e 'using Pkg;Pkg.develop(PackageSpec(path=pwd()));Pkg.add(PackageSpec(name="Compose",version="0.8"));Pkg.develop(PackageSpec(url="https://github.com/esa-esdl/ESDLPlots.jl"));'
        - julia --project=docs docs/make.jl
      name: "HTML"
      after_success: skip
after_success:
    - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
