# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 0.7
  - 1.0
notifications:
  email: false
before_install:
  - sudo apt-get install -y libnetcdf-dev libhdf5-dev netcdf-bin

after_success:
  - julia -e 'Pkg.add("Documenter")'
  - julia -e 'Pkg.clone("https://github.com/esa-esdl/ESDLPlots.jl");Pkg.add("GR")'
  - julia -e 'using Compose'
  - julia -e 'cd(Pkg.dir("ESDL")); include(joinpath("docs", "make.jl"))'
