language: julia
os:
    - osx
    - linux
julia:
    - 1.3
notifications:
    email: false
jobs:
  include:
    - stage: "Documentation"
      julia: 1.3
      os: linux
      script:
        - julia --project=docs -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate(); Pkg.add(PackageSpec(url="https://github.com/esa-esdl/ESDLPlots.jl"))'
        - julia --project=docs -e 'using Pkg; Pkg.add(PackageSpec(name="Compose", rev="master"))'
        - travis_wait 30 julia --project=docs docs/make.jl
      name: "HTML"
      after_success: skip
after_success:
    - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
